### PR TITLE
Create tnb_contact.html

### PR DESCRIPTION
**Pull request by ghost**
TNB form page

### CODE REVIEW

**Comment by manishram** [comment]
### Please close this PR
Reasons:
- What you used as a reference is just a rough sketch I gave. The design team is working on actual designs.
- This is a design repo. The website's front-end codes are here: https://github.com/thenewboston-developers/Website
- We are using **React** for the front-end.

**Comment by 54m50nd33n** [comment]
Ok

On Tuesday, March 9, 2021, Manish Ram ***@***.***> wrote:
> Please close this PR
>
> Reasons:
>
> What you used as a reference is just a rough sketch I gave. The design
team is working on actual designs.
> This is a design repo. The website's front-end codes are here:
https://github.com/thenewboston-developers/Website
> We are using React for the front-end.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci3.googleusercontent.com/proxy/IoW3-KQCbTUxpp2zIgkFJwRliWaWz86p439RYyK8ZIv8OhraMOVKaPjQ97rfpLktYbnwcB7-p36Y67uISXc9-wkG3_cosHHi2FpSZT4XItQ1kNUa4T2-h52gYvvyIfhxzSu3iYVMn8NE96Q_7TO5pC5e3xHSwtVdaeUUgBiCkK8X5UUCG2ecKyvgWIgG_ceY4p56VkgwBjA21h-kNiX-b6cKqPs4o1ncQLIA6bwErA=s0-d-e1-ft#https://github.com/notifications/beacon/ASY5LXLWVNBV36QG2MLGLITTCZRZBA5CNFSM4YUN63PKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOF5LZLSA.gif>

**Comment by 54m50nd33n** [comment]
Closing PR

**Comment by 54m50nd33n** [comment]
Closing PR

**Pull request closed without merging**
